version: 2
jobs:
  build-everything:
    machine: true
    working_directory: ~/crawlab
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-go
      - run: |
          echo "$ali_pass" | docker login registry.cn-hongkong.aliyuncs.com -u "$ali_user" --password-stdin
          echo "$ali_pass" | docker login registry.cn-shanghai.aliyuncs.com -u "$ali_user" --password-stdin
          echo "$docker_pass" | docker login -u "$docker_user" --password-stdin
          docker build -t hehety/crawlab:latest .
          docker tag hehety/crawlab:latest registry.cn-hongkong.aliyuncs.com/hehety/crawlab:latest
          docker tag hehety/crawlab:latest registry.cn-shanghai.aliyuncs.com/hehety/crawlab:latest
          docker push hehety/crawlab:latest
          docker push registry.cn-hongkong.aliyuncs.com/hehety/crawlab:latest
          docker push registry.cn-shanghai.aliyuncs.com/hehety/crawlab:latest
      - save_cache:
          paths:
            - ~/go
          key: v1-dependencies-go
workflows:
  version: 2
  build-all:
    jobs:
      - build-everything
